---
repositories:
  - name: incubator
    url: http://storage.googleapis.com/kubernetes-charts-incubator

releases:
  - name: secrets-example
    namespace: default
    chart: incubator/raw
    version: 0.2.3
    installed: true
    labels:
      namespace: default
      chart: raw
    values:
      - resources:
          - apiVersion: v1
            kind: Secret
            metadata:
              name: workaround
            type: Opaque
            data:
              secret: {{ .Values.foo.bar }}
